### ISSUE TITLE
not working via i2c mux tca9548a

### ISSUE THREAD

**Issue by viotemp1** [Seeed-Studio/Grove_Gesture#10]
Hello,

Is there any way to make it working with i2c mux tca9548a?
Regards

**Comment by Lesords** [comment]
Hello,

I'm very sorry to have kept you waiting so long.

Do you still have this problem now?

**Comment by Lesords** [comment]
Hello,

I\'m going to close this issue, feel free to re-open it if you have any other questions.

[Autocommentary]
