### ISSUE TITLE
Problem with Continuous Rotation Gesture Detection

### ISSUE THREAD

**Issue by devenv2** [Seeed-Studio/Grove_Gesture#13]
**Issue:**

I'm experiencing an issue with detecting continuous rotation gestures using the PAJ7620 library. The sensor only registers a rotation gesture once when it starts and does not continuously detect the rotation. This results in a lack of smooth feedback in applications where continuous rotation is expected, such as rotating a virtual object.

**Description**:

When performing a rotation gesture, such as rotating an object on the screen, the sensor only reports the gesture when the rotation stops. This is problematic for applications requiring continuous updates during the rotation. For example, if I rotate my finger in a circular motion, the application should continuously receive rotation events and update the visual representation accordingly.

**Steps to Reproduce:**

Initialize the PAJ7620 sensor using the library.
Perform a continuous rotation gesture with the sensor.
Observe that the sensor only reports the gesture when it stops, not continuously during the rotation.
Expected Behavior:

The sensor should continuously report rotation gestures while the rotation is happening, allowing the application to provide real-time feedback and updates.

**Current Behavior:**

The sensor reports the rotation gesture only once, usually when the rotation stops, leading to a delay in feedback and lack of smooth interaction.

**Suggested Improvement:**

Modify the library to detect and report rotation gestures continuously while the gesture is being performed.
Ensure that the sensor readings are processed in a way that reflects continuous motion, rather than discrete events.

**Thank you for your help with this issue.**

**Comment by Lesords** [comment]
Hello,

I'm very sorry to have kept you waiting so long.

Do you still have this problem now?

**Comment by Lesords** [comment]
Hello,

I\'m going to close this issue, feel free to re-open it if you have any other questions.

[Autocommentary]
