### ISSUE TITLE
Proximity detection function

### ISSUE THREAD

**Issue by Gbouna** [Seeed-Studio/Grove_Gesture#9]
Thank you for the repo and the examples, extremely informative and helpful. 
The data sheet of PAJ7620 says it has an in-built function for proximity detection for the purpose of sensing objects approaching and departing.  I would want to know how to implement this, do you have some examples implementing this? I will really appreciate if you can share them with me. 
Thank you.

**Comment by Lesords** [comment]
Hello,

I'm very sorry to have kept you waiting so long.

Do you still have this problem now?

**Comment by Lesords** [comment]
Hello,

I\'m going to close this issue, feel free to re-open it if you have any other questions.

[Autocommentary]
